global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rag-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['rag-api:9090']

  - job_name: 'qdrant'
    metrics_path: /metrics
    static_configs:
      - targets: ['qdrant:6333']

  - job_name: 'document-processor'
    metrics_path: /metrics
    static_configs:
      - targets: ['document-processor:9090']